# https://taskfile.dev

version: '2'

tasks:
  vet:
    cmds:
      - go vet
  build:
    cmds:
      - go install
  test:
    cmds:
      - go test ./validate
  defualt:
    cmds:
      - task: test
